[tool.poetry]
name = "netwarden"
version = "0.1.0"
description = ""
authors = ["Dmitry Figol <git@dmfigol.me>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
fastapi = "^0.52.0"
uvicorn = "^0.11.3"
httpx = "^0.11.1"

[tool.poetry.dev-dependencies]
bpython = "^0.18"
pdbpp = "^0.10.2"
flake8 = "^3.7.9"
mypy = "^0.761"
black = "^19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
